#!/usr/bin/env bash
set -e

ROOT=besa-sqlverse
echo "📁 creating $ROOT ..."
mkdir -p $ROOT/{infra,.github/workflows,scripts,docs,cases,datasets,packages/{shared,frontend/styles,backend/app}}

# --- helper to write files ---
write() { fp="$ROOT/$1"; mkdir -p "$(dirname "$fp")"; cat >"$fp"; }

############################################################
# root-level files
############################################################
write ".env.example" <<'EOF'
DATABASE_URL=postgres://besa:besa@localhost:5432/besa
FLY_API_TOKEN=
EOF

write "Dockerfile.multi" <<"EOF"
# (paste the Dockerfile.multi content from canvas here)
EOF

write "Makefile" <<"EOF"
# (paste Makefile content here)
EOF

write "fly.toml" <<"EOF"
# (paste fly.toml content here)
EOF

write "dataset_registry.yaml" <<"EOF"
# (paste full dataset_registry.yaml content here)
EOF

write "curriculum_blueprints.yaml" <<"EOF"
# (paste full curriculum_blueprints.yaml here)
EOF

write "package.json" <<"EOF"
# (paste root package.json text here)
EOF

write "pnpm-workspace.yaml" <<"EOF"
packages:
  - "packages/*"
EOF

write "tsconfig.base.json" <<"EOF"
{ "compilerOptions": { "target": "ES2021","module": "ESNext","moduleResolution":"Node","jsx":"preserve","strict":true,"skipLibCheck":true,"forceConsistentCasingInFileNames":true } }
EOF

write "turbo.json" <<"EOF"
{ "$schema":"https://turbo.build/schema.json","pipeline":{"dev":{"cache":false}} }
EOF

############################################################
# infra
############################################################
write "infra/docker-compose.yml" <<"EOF"
# (lightweight compose file from canvas)
EOF

write "infra/docker-compose.full.yml" <<"EOF"
# (full compose file with frontend/backend/db/nginx)
EOF

write "infra/nginx.conf" <<"EOF"
# (nginx.conf from canvas)
EOF

############################################################
# GitHub workflows
############################################################
write ".github/workflows/deploy.yml" <<"EOF"
# (deploy.yml content)
EOF

write ".github/workflows/pages.yml" <<"EOF"
# (pages.yml content)
EOF

############################################################
# scripts
############################################################
write "scripts/gen_curriculum.py" <<"EOF"
# (full gen_curriculum.py)
EOF
write "scripts/build_docs.py" <<"EOF"
# (full build_docs.py)
EOF
write "scripts/fetch_real_data.py" <<"EOF"
# (full fetch_real_data.py)
EOF
write "scripts/seed_db.py" <<"EOF"
# (full seed_db.py)
EOF
write "scripts/export_portfolio.sh" <<"EOF"
# (full export_portfolio.sh)
EOF
chmod +x "$ROOT/scripts/export_portfolio.sh"

write "scripts/test_cases.mjs" <<"EOF"
# (full test_cases.mjs)
EOF

############################################################
# docs placeholder (generated later)
############################################################
mkdir -p $ROOT/docs
echo "# will be generated by make curriculum" >"$ROOT/docs/learning-path.md"

############################################################
# packages/shared
############################################################
write "packages/shared/package.json" <<"EOF"
{ "name":"@besa/shared","version":"0.0.1","type":"module","main":"dist/index.js","types":"dist/index.d.ts","files":["dist"],"scripts":{"build":"tsc -p ."},"dependencies":{"yaml":"^2.4.2"} }
EOF

write "packages/shared/src/caseSchema.ts" <<"EOF"
export interface Case {
  id: string; tier: number; domain: string; name: string;
  description: string; datasets: {name:string;file:string}[];
  seedQuery: string; expected: Record<string,unknown>[]; hints: string[];
  skills?: string[]; dataset_key?: string; prereq_cases?: string[];
}
EOF

############################################################
# packages/backend
############################################################
write "packages/backend/requirements.txt" <<"EOF"
fastapi==0.111.0
uvicorn[standard]==0.30.0
asyncpg==0.29.0
sqlalchemy==2.0.29
alembic==1.13.1
python-dotenv==1.0.1
EOF

write "packages/backend/alembic.ini" <<"EOF"
[alembic]
script_location = packages/backend/migrations
sqlalchemy.url = env:DATABASE_URL
EOF

write "packages/backend/app/main.py" <<"EOF"
# (FastAPI main.py from canvas)
EOF

write "packages/backend/app/models.py" <<"EOF"
# (models.py from canvas)
EOF

write "packages/backend/.env.example" <<"EOF"
DATABASE_URL=postgres://besa:besa@localhost:5432/besa
EOF

############################################################
# packages/frontend
############################################################
write "packages/frontend/package.json" <<"EOF"
# (frontend package.json)
EOF
write "packages/frontend/next.config.js" <<"EOF"
module.exports = { experimental: { appDir: true } };
EOF
write "packages/frontend/tailwind.config.js" <<"EOF"
module.exports = { content:['./app/**/*.{ts,tsx}','./components/**/*.{ts,tsx}'],theme:{extend:{}},plugins:[]};
EOF
write "packages/frontend/postcss.config.js" <<"EOF"
module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };
EOF
write "packages/frontend/tsconfig.json" <<"EOF"
{ "extends":"../../tsconfig.base.json","compilerOptions":{"baseUrl":".","paths":{"@/components/*":["components/*"],"@/lib/*":["lib/*"]}} }
EOF

mkdir -p $ROOT/packages/frontend/app $ROOT/packages/frontend/components $ROOT/packages/frontend/lib
write "packages/frontend/app/layout.tsx" <<"EOF"
// (layout.tsx content)
EOF
write "packages/frontend/app/page.tsx" <<"EOF"
// (page.tsx content)
EOF
write "packages/frontend/components/SQLPlayground.tsx" <<"EOF"
// (SQLPlayground.tsx content)
EOF
write "packages/frontend/components/Table.tsx" <<"EOF"
// (Table.tsx content)
EOF
write "packages/frontend/lib/duckdbClient.ts" <<"EOF"
// (duckdbClient.ts content)
EOF
write "packages/frontend/styles/globals.css" <<"EOF"
@tailwind base; @tailwind components; @tailwind utilities;
html{scroll-behavior:smooth;} code{@apply px-1 py-0.5 bg-gray-100 rounded;}
EOF

echo "✅ All files and folders created under $ROOT"
