import type { CloudMission } from './types';

// Microsoft Azure Fundamentals + Solutions Architect (AZ-900 / AZ-305) track.
export const azureMissions: CloudMission[] = [
  {
    slug: 'azure-fundamentals',
    title: 'Azure Fundamentals: Regions, Resource Groups & Subscriptions',
    section: 'Core',
    level: 'Beginner',
    stars: 1,
    skills: ['resource-groups', 'subscriptions', 'management-groups'],
    description:
      'Azure organizes everything into a hierarchy: Management Group → Subscription → Resource Group → Resource. Learn regions, availability zones, and how billing rolls up through this tree.',
    prerequisites: [],
    labType: 'diagram',
  },
  {
    slug: 'azure-compute',
    title: 'Virtual Machines & App Service',
    section: 'Compute',
    level: 'Beginner',
    stars: 1,
    skills: ['vm', 'app-service', 'scale-sets'],
    description:
      'Run IaaS VMs and PaaS App Service web apps. Use Virtual Machine Scale Sets for elastic compute and understand when to pick managed PaaS over raw VMs.',
    prerequisites: ['azure-fundamentals'],
    labType: 'iac',
  },
  {
    slug: 'azure-storage',
    title: 'Blob, Queue, Table & File Storage',
    section: 'Storage',
    level: 'Beginner',
    stars: 1,
    skills: ['blob', 'storage-account', 'access-tiers'],
    description:
      'A Storage Account hosts Blob, Queue, Table and File services. Learn Hot/Cool/Archive access tiers and redundancy options (LRS, ZRS, GRS).',
    prerequisites: ['azure-fundamentals'],
    labType: 'diagram',
  },
  {
    slug: 'azure-networking',
    title: 'VNet, NSG, Load Balancer & App Gateway',
    section: 'Networking',
    level: 'Intermediate',
    stars: 2,
    skills: ['vnet', 'nsg', 'app-gateway'],
    description:
      'Build a Virtual Network with subnets, secure it with Network Security Groups, and route traffic with Azure Load Balancer (L4) and Application Gateway (L7 + WAF).',
    prerequisites: ['azure-fundamentals'],
    labType: 'iac',
  },
  {
    slug: 'azure-iam',
    title: 'Entra ID, RBAC & Conditional Access',
    section: 'IAM',
    level: 'Intermediate',
    stars: 2,
    skills: ['entra-id', 'rbac', 'mfa', 'pim'],
    description:
      'Microsoft Entra ID (formerly Azure AD) is Azure\'s identity backbone. Assign RBAC roles at the right scope, enforce Conditional Access + MFA, and use PIM for just-in-time admin.',
    prerequisites: ['azure-fundamentals'],
    labType: 'diagram',
  },
  {
    slug: 'azure-databases',
    title: 'Azure SQL, Cosmos DB & Cache for Redis',
    section: 'Databases',
    level: 'Intermediate',
    stars: 2,
    skills: ['azure-sql', 'cosmos-db', 'redis'],
    description:
      'Pick the right data store: Azure SQL (relational, managed), Cosmos DB (globally distributed NoSQL with tunable consistency), and Cache for Redis for low-latency reads.',
    prerequisites: ['azure-compute'],
    labType: 'iac',
  },
  {
    slug: 'azure-serverless',
    title: 'Functions, Logic Apps & Event Grid',
    section: 'Serverless',
    level: 'Intermediate',
    stars: 2,
    skills: ['functions', 'logic-apps', 'event-grid'],
    description:
      'Build event-driven serverless apps with Azure Functions, orchestrate SaaS connectors with Logic Apps, and route events at scale with Event Grid.',
    prerequisites: ['azure-compute'],
    labType: 'iac',
  },
  {
    slug: 'azure-containers',
    title: 'AKS, Container Instances & Registry',
    section: 'Containers',
    level: 'Advanced',
    stars: 3,
    skills: ['aks', 'aci', 'acr', 'kubernetes'],
    description:
      'Run Kubernetes on AKS, quick one-off containers on ACI, and store images in Azure Container Registry. Understand node pools, scaling, and ingress.',
    prerequisites: ['azure-serverless'],
    labType: 'iac',
  },
  {
    slug: 'azure-monitoring',
    title: 'Azure Monitor, Log Analytics & App Insights',
    section: 'Monitoring',
    level: 'Intermediate',
    stars: 2,
    skills: ['monitor', 'log-analytics', 'app-insights'],
    description:
      'Collect metrics and logs with Azure Monitor, query them with KQL in Log Analytics, and trace application performance with Application Insights.',
    prerequisites: ['azure-compute'],
    labType: 'diagram',
  },
  {
    slug: 'azure-security',
    title: 'Defender for Cloud, Key Vault & DDoS',
    section: 'Security',
    level: 'Advanced',
    stars: 3,
    skills: ['defender', 'key-vault', 'ddos'],
    description:
      'Harden your estate with Microsoft Defender for Cloud secure score, store secrets in Key Vault, and protect public endpoints with DDoS Protection.',
    prerequisites: ['azure-iam'],
    labType: 'diagram',
  },
  {
    slug: 'azure-iac',
    title: 'ARM Templates & Bicep',
    section: 'IaC',
    level: 'Advanced',
    stars: 3,
    skills: ['arm', 'bicep', 'terraform-azure'],
    description:
      'Deploy infrastructure declaratively with ARM JSON, then with cleaner Bicep syntax. Compare with Terraform for Azure.',
    prerequisites: ['azure-networking'],
    labType: 'iac',
  },
  {
    slug: 'azure-ha',
    title: 'Availability Zones, Traffic Manager & Site Recovery',
    section: 'HA & DR',
    level: 'Advanced',
    stars: 3,
    skills: ['availability-zones', 'traffic-manager', 'asr'],
    description:
      'Design for resilience with Availability Zones, route globally with Traffic Manager / Front Door, and plan disaster recovery with Azure Site Recovery.',
    prerequisites: ['azure-networking'],
    labType: 'diagram',
  },
  {
    slug: 'azure-cost',
    title: 'Cost Management & Reserved Instances',
    section: 'Cost',
    level: 'Intermediate',
    stars: 2,
    skills: ['cost-management', 'reserved', 'budgets'],
    description:
      'Track spend with Cost Management, set budgets + alerts, and commit to Reserved Instances / Savings Plans for predictable workloads.',
    prerequisites: ['azure-fundamentals'],
    labType: 'diagram',
  },
  {
    slug: 'azure-devops',
    title: 'Azure DevOps Pipelines & GitHub Actions',
    section: 'DevOps',
    level: 'Advanced',
    stars: 3,
    skills: ['devops', 'pipelines', 'ci-cd'],
    description:
      'Build CI/CD pipelines with Azure DevOps and GitHub Actions: build, test, scan, and deploy to App Service / AKS with approvals and environments.',
    prerequisites: ['azure-iac'],
    labType: 'iac',
  },
  {
    slug: 'azure-data',
    title: 'Data Factory, Synapse & Data Lake',
    section: 'Data',
    level: 'Advanced',
    stars: 3,
    skills: ['adf', 'synapse', 'adls'],
    description:
      'Ingest with Azure Data Factory, store in ADLS Gen2, and analyze at scale with Synapse Analytics. Foundation for enterprise data + ESG reporting platforms.',
    prerequisites: ['azure-databases'],
    labType: 'iac',
  },
  {
    slug: 'azure-capstone',
    title: 'Azure Capstone: Enterprise 3-Tier Architecture',
    section: 'Capstone',
    level: 'Master',
    stars: 5,
    skills: ['everything'],
    description:
      'Design an enterprise-grade architecture: App Gateway (WAF) → App Service / AKS → Azure SQL with geo-replication, secured by Entra ID + Key Vault, deployed via Bicep, observed with Azure Monitor.',
    prerequisites: ['azure-data', 'azure-ha', 'azure-security'],
    labType: 'iac',
  },
  {
    slug: 'az305-simulator',
    title: 'AZ-305 Exam Simulator',
    section: 'Bonus',
    level: 'Expert',
    stars: 4,
    skills: ['exam-prep'],
    description:
      'Timed AZ-305 Designing Microsoft Azure Infrastructure Solutions mock exam with scenario design questions and explanations.',
    prerequisites: ['azure-capstone'],
    labType: 'quiz',
    isBonus: true,
  },
  {
    slug: 'azure-green',
    title: 'Sustainable Azure: Emissions Impact Dashboard',
    section: 'Bonus',
    level: 'Expert',
    stars: 4,
    skills: ['sustainability', 'emissions', 'cloud-for-sustainability'],
    description:
      'Use the Microsoft Emissions Impact Dashboard and Microsoft Cloud for Sustainability to measure and reduce the carbon footprint of your Azure workloads.',
    prerequisites: ['azure-capstone'],
    labType: 'diagram',
    isBonus: true,
    crossDomain: 'esg',
  },
];
