import type { CloudMission } from './types';

// Google Cloud Associate Cloud Engineer + Professional Cloud Architect track.
export const gcpMissions: CloudMission[] = [
  {
    slug: 'gcp-fundamentals',
    title: 'GCP Projects, Billing & IAM',
    section: 'Core',
    level: 'Beginner',
    stars: 1,
    skills: ['projects', 'billing', 'iam'],
    description:
      'In GCP the project is the unit of isolation. Learn the Organization → Folder → Project hierarchy, billing accounts, and IAM roles/bindings.',
    prerequisites: [],
    labType: 'diagram',
  },
  {
    slug: 'compute-engine',
    title: 'Compute Engine: VMs, Images & Machine Types',
    section: 'Compute',
    level: 'Beginner',
    stars: 1,
    skills: ['gce', 'instance-groups', 'preemptible'],
    description:
      'Launch Compute Engine VMs, use custom images and managed instance groups for autoscaling, and save big with preemptible / Spot VMs.',
    prerequisites: ['gcp-fundamentals'],
    labType: 'diagram',
  },
  {
    slug: 'cloud-run',
    title: 'Serverless Containers with Cloud Run',
    section: 'Serverless',
    level: 'Intermediate',
    stars: 2,
    skills: ['cloud-run', 'containers', 'knative'],
    description:
      'Deploy any container that listens on a port and let Cloud Run scale it to zero and back. Built on Knative — fully managed, request-based billing.',
    prerequisites: ['compute-engine'],
    labType: 'iac',
  },
  {
    slug: 'gke',
    title: 'Kubernetes on GKE',
    section: 'Containers',
    level: 'Advanced',
    stars: 3,
    skills: ['gke', 'kubernetes', 'autopilot'],
    description:
      'Run Kubernetes the Google way. Compare Standard mode (you manage nodes) vs Autopilot (Kubernetes without the existential dread — Google manages the nodes).',
    prerequisites: ['cloud-run'],
    labType: 'iac',
  },
  {
    slug: 'cloud-storage',
    title: 'Cloud Storage: Buckets, Classes & Transfer',
    section: 'Storage',
    level: 'Beginner',
    stars: 1,
    skills: ['gcs', 'nearline', 'coldline'],
    description:
      'Store objects in GCS buckets across Standard, Nearline, Coldline and Archive classes. Use lifecycle rules and Storage Transfer Service for migration.',
    prerequisites: ['gcp-fundamentals'],
    labType: 'diagram',
  },
  {
    slug: 'vpc-gcp',
    title: 'VPC, Firewall Rules & Cloud NAT',
    section: 'Networking',
    level: 'Intermediate',
    stars: 2,
    skills: ['vpc', 'firewall', 'cloud-nat', 'shared-vpc'],
    description:
      'GCP VPCs are global. Configure subnets per region, firewall rules, Cloud NAT for private egress, and Shared VPC for multi-project networking.',
    prerequisites: ['gcp-fundamentals'],
    labType: 'iac',
  },
  {
    slug: 'cloud-sql-spanner',
    title: 'Cloud SQL, Spanner & Firestore',
    section: 'Databases',
    level: 'Intermediate',
    stars: 2,
    skills: ['cloud-sql', 'spanner', 'firestore'],
    description:
      'Choose between Cloud SQL (managed MySQL/Postgres), Spanner (globally consistent relational at scale), and Firestore (serverless document DB).',
    prerequisites: ['vpc-gcp'],
    labType: 'diagram',
  },
  {
    slug: 'bigquery',
    title: 'BigQuery: Serverless Analytics at Petabyte Scale',
    section: 'Data',
    level: 'Intermediate',
    stars: 2,
    skills: ['bigquery', 'sql', 'partitioning', 'bq-ml'],
    description:
      'BigQuery is a game-changer: serverless SQL analytics over petabytes. Learn partitioning + clustering for cost control and train models in-place with BigQuery ML.',
    prerequisites: ['cloud-sql-spanner'],
    labType: 'iac',
  },
  {
    slug: 'pub-sub',
    title: 'Pub/Sub & Dataflow: Event-Driven Pipelines',
    section: 'App Integration',
    level: 'Advanced',
    stars: 3,
    skills: ['pubsub', 'dataflow', 'datastream'],
    description:
      'Ingest events globally with Pub/Sub and process streaming or batch data with Dataflow (Apache Beam). The backbone of real-time analytics on GCP.',
    prerequisites: ['bigquery'],
    labType: 'iac',
  },
  {
    slug: 'gcp-security',
    title: 'Cloud Armor, Secret Manager & VPC-SC',
    section: 'Security',
    level: 'Advanced',
    stars: 3,
    skills: ['cloud-armor', 'secret-manager', 'vpc-sc'],
    description:
      'Defend apps with Cloud Armor (WAF + DDoS), store secrets in Secret Manager, and build data-exfiltration perimeters with VPC Service Controls.',
    prerequisites: ['vpc-gcp'],
    labType: 'diagram',
  },
  {
    slug: 'cloud-monitoring',
    title: 'Cloud Monitoring, Logging & Error Reporting',
    section: 'Monitoring',
    level: 'Intermediate',
    stars: 2,
    skills: ['monitoring', 'logging', 'trace'],
    description:
      'Use the Google Cloud Operations suite: Monitoring dashboards + alerts, centralized Logging, distributed Trace, and Error Reporting.',
    prerequisites: ['compute-engine'],
    labType: 'diagram',
  },
  {
    slug: 'terraform-gcp',
    title: 'Terraform on GCP: IaC Best Practices',
    section: 'IaC',
    level: 'Advanced',
    stars: 3,
    skills: ['terraform', 'modules', 'remote-state'],
    description:
      'Provision GCP with Terraform. Structure reusable modules, manage remote state in GCS, and run plan/apply in CI.',
    prerequisites: ['vpc-gcp'],
    labType: 'iac',
  },
  {
    slug: 'vertex-ai',
    title: 'Vertex AI: Train & Deploy ML Models',
    section: 'AI/ML',
    level: 'Advanced',
    stars: 3,
    skills: ['vertex-ai', 'automl', 'pipelines'],
    description:
      'Train custom and AutoML models on Vertex AI, build reproducible ML pipelines, and deploy to managed endpoints.',
    prerequisites: ['bigquery'],
    labType: 'iac',
  },
  {
    slug: 'gcp-cost',
    title: 'Committed Use Discounts & Preemptible VMs',
    section: 'Cost',
    level: 'Intermediate',
    stars: 2,
    skills: ['cud', 'preemptible', 'budgets'],
    description:
      'Cut costs with Committed Use Discounts, preemptible/Spot VMs for fault-tolerant batch work, and budget alerts.',
    prerequisites: ['compute-engine'],
    labType: 'diagram',
  },
  {
    slug: 'gcp-ha',
    title: 'Regional vs Global Load Balancing & CDN',
    section: 'HA & DR',
    level: 'Advanced',
    stars: 3,
    skills: ['cloud-lb', 'cloud-cdn', 'failover'],
    description:
      'Design highly available systems with global HTTP(S) Load Balancing, Cloud CDN, and multi-region failover.',
    prerequisites: ['vpc-gcp'],
    labType: 'diagram',
  },
  {
    slug: 'gcp-capstone',
    title: 'GCP Capstone: Data Analytics Platform',
    section: 'Capstone',
    level: 'Master',
    stars: 5,
    skills: ['everything'],
    description:
      'Build an end-to-end analytics platform: Pub/Sub → Dataflow → BigQuery → Looker Studio, served via Cloud Run, secured with IAM + VPC-SC, provisioned with Terraform.',
    prerequisites: ['pub-sub', 'gcp-security', 'gcp-ha'],
    labType: 'iac',
  },
  {
    slug: 'pca-simulator',
    title: 'Professional Cloud Architect Exam Simulator',
    section: 'Bonus',
    level: 'Expert',
    stars: 4,
    skills: ['exam-prep'],
    description:
      'Timed PCA mock exam with case-study style scenario questions (à la TerramEarth / Mountkirk) and explanations.',
    prerequisites: ['gcp-capstone'],
    labType: 'quiz',
    isBonus: true,
  },
  {
    slug: 'gcp-carbon',
    title: 'Carbon Footprint API & GCP Green Regions',
    section: 'Bonus',
    level: 'Expert',
    stars: 4,
    skills: ['carbon-footprint-api', 'green-regions', 'cfe'],
    description:
      'Pull per-project emissions from the GCP Carbon Footprint API into BigQuery, visualize in Looker Studio, and pick low-CO2 / Carbon-Free-Energy regions.',
    prerequisites: ['gcp-capstone'],
    labType: 'iac',
    isBonus: true,
    crossDomain: 'esg',
  },
];
