export interface VisualizationConfig {
  query: string;
  type: 'bar' | 'line' | 'pie' | 'histogram' | 'scatter' | 'heatmap';
  layout: {
    title: { text: string };
    xaxis?: { title?: { text: string }; tickangle?: number };
    yaxis?: { title?: { text: string } };
    font?: { family: string; color: string };
    margin?: { t: number; b: number; l: number; r: number };
  };
  x_col: string;
  y_col?: string | null;
  z_col?: string | null;
  group_col?: string | null;
  dataMapper: (data: any[]) => any;
}

export const visualizationConfigs: Record<string, Record<string, VisualizationConfig[]>> = {
  business: {
    basics_select: [
      {
        query: `SELECT product_line, SUM(total) as total_sales FROM business_retail GROUP BY product_line ORDER BY total_sales DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Sales by Product Line' },
          xaxis: { title: { text: 'Product Line' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Sales ($)' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'product_line',
        y_col: 'total_sales',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.product_line),
          y: data.map((row) => row.total_sales),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    agg_revenue: [
      {
        query: `SELECT product_line, SUM(total) as total_revenue FROM business_retail GROUP BY product_line ORDER BY total_revenue DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Revenue by Product Line' },
          xaxis: { title: { text: 'Product Line' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Revenue ($)' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'product_line',
        y_col: 'total_revenue',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.product_line),
          y: data.map((row) => row.total_revenue),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
      {
        query: `SELECT strftime('%Y-%m', date) as month, SUM(total) as total_revenue FROM business_retail GROUP BY strftime('%Y-%m', date) ORDER BY month;`,
        type: 'line',
        layout: {
          title: { text: 'Revenue Over Time' },
          xaxis: { title: { text: 'Month' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Revenue ($)' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'month',
        y_col: 'total_revenue',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.month),
          y: data.map((row) => row.total_revenue),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
      {
        query: `SELECT product_line, branch, SUM(total) as total_sales FROM business_retail GROUP BY product_line, branch;`,
        type: 'heatmap',
        layout: {
          title: { text: 'Sales by Product Line and Branch' },
          xaxis: { title: { text: 'Branch' } },
          yaxis: { title: { text: 'Product Line' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'branch',
        y_col: 'product_line',
        z_col: 'total_sales',
        group_col: null,
        dataMapper: (data) => ({
          x: [...new Set(data.map((row) => row.branch))],
          y: [...new Set(data.map((row) => row.product_line))],
          z: data.map((row) => row.total_sales),
          type: 'heatmap',
          colorscale: 'Viridis',
        }),
      },
    ],
    joins_returns: [
      {
        query: `SELECT r.return_reason, COUNT(*) as return_count FROM business_retail b JOIN returns r ON b.invoice_id = r.invoice_id GROUP BY r.return_reason ORDER BY return_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Returns by Reason' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'return_reason',
        y_col: 'return_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.return_reason),
          values: data.map((row) => row.return_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
    window_cumsum: [
      {
        query: `SELECT branch, date, SUM(total) OVER (PARTITION BY branch ORDER BY date) as cumulative_sales FROM business_retail ORDER BY branch, date;`,
        type: 'line',
        layout: {
          title: { text: 'Cumulative Sales by Branch' },
          xaxis: { title: { text: 'Date' }, tickangle: 45 },
          yaxis: { title: { text: 'Cumulative Sales ($)' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'date',
        y_col: 'cumulative_sales',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.date),
          y: data.map((row) => row.cumulative_sales),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_profit: [
      {
        query: `WITH ReturnTotals AS ( SELECT b.branch, SUM(b.total) as return_total FROM business_retail b JOIN returns r ON b.invoice_id = r.invoice_id GROUP BY b.branch ) SELECT b.branch, SUM(b.total) - COALESCE(r.return_total, 0) as net_profit FROM business_retail b LEFT JOIN ReturnTotals r ON b.branch = r.branch GROUP BY b.branch ORDER BY net_profit DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Net Profit by Branch' },
          xaxis: { title: { text: 'Branch' }, tickangle: 45 },
          yaxis: { title: { text: 'Net Profit ($)' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'branch',
        y_col: 'net_profit',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.branch),
          y: data.map((row) => row.net_profit),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_root: [
      {
        query: `SELECT customer_type, COUNT(*) as sales_count FROM business_retail GROUP BY customer_type ORDER BY sales_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Sales Distribution by Customer Type' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'customer_type',
        y_col: 'sales_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.customer_type),
          values: data.map((row) => row.sales_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
  },
  healthcare: {
    patient_select: [
      {
        query: `SELECT age, COUNT(*) as patient_count FROM patients GROUP BY age ORDER BY age;`,
        type: 'histogram',
        layout: {
          title: { text: 'Age Distribution of Patients' },
          xaxis: { title: { text: 'Age' } },
          yaxis: { title: { text: 'Patient Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'age',
        y_col: null,
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.age),
          type: 'histogram',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    diagnosis_count: [
      {
        query: `SELECT diagnosis, COUNT(*) as diagnosis_count FROM treatments GROUP BY diagnosis ORDER BY diagnosis_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Diagnosis Distribution' },
          xaxis: { title: { text: 'Diagnosis' }, tickangle: 45 },
          yaxis: { title: { text: 'Diagnosis Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'diagnosis',
        y_col: 'diagnosis_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.diagnosis),
          y: data.map((row) => row.diagnosis_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    treatment_joins: [
      {
        query: `SELECT t.diagnosis, COUNT(*) as treatment_count FROM patients p JOIN treatments t ON p.patient_id = t.patient_id GROUP BY t.diagnosis ORDER BY treatment_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Treatments by Diagnosis' },
          xaxis: { title: { text: 'Diagnosis' }, tickangle: 45 },
          yaxis: { title: { text: 'Treatment Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'diagnosis',
        y_col: 'treatment_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.diagnosis),
          y: data.map((row) => row.treatment_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    admission_trend: [
      {
        query: `SELECT strftime('%Y-%m', admission_date) as month, COUNT(*) as admission_count FROM admissions GROUP BY strftime('%Y-%m', admission_date) ORDER BY month;`,
        type: 'line',
        layout: {
          title: { text: 'Admissions Over Time' },
          xaxis: { title: { text: 'Month' }, tickangle: 45 },
          yaxis: { title: { text: 'Admission Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'month',
        y_col: 'admission_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.month),
          y: data.map((row) => row.admission_count),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_treatment: [
      {
        query: `SELECT diagnosis, COUNT(*) as treatment_count FROM treatments GROUP BY diagnosis ORDER BY treatment_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Treatment Counts by Diagnosis' },
          xaxis: { title: { text: 'Diagnosis' }, tickangle: 45 },
          yaxis: { title: { text: 'Treatment Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'diagnosis',
        y_col: 'treatment_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.diagnosis),
          y: data.map((row) => row.treatment_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_health: [
      {
        query: `SELECT t.diagnosis, COUNT(DISTINCT p.patient_id) as patient_count FROM patients p JOIN treatments t ON p.patient_id = t.patient_id JOIN admissions a ON p.patient_id = a.patient_id GROUP BY t.diagnosis ORDER BY patient_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Patient Admissions by Diagnosis' },
          xaxis: { title: { text: 'Diagnosis' }, tickangle: 45 },
          yaxis: { title: { text: 'Patient Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'diagnosis',
        y_col: 'patient_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.diagnosis),
          y: data.map((row) => row.patient_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
  },
  crime: {
    crime_select: [
      {
        query: `SELECT primary_type, COUNT(*) as crime_count FROM crime_chicago GROUP BY primary_type ORDER BY crime_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Crimes by Type' },
          xaxis: { title: { text: 'Crime Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Crime Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'primary_type',
        y_col: 'crime_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.primary_type),
          y: data.map((row) => row.crime_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    crime_by_area: [
      {
        query: `SELECT location_description, COUNT(*) as crime_count FROM crime_chicago GROUP BY location_description ORDER BY crime_count DESC LIMIT 10;`,
        type: 'bar',
        layout: {
          title: { text: 'Top 10 Crime Locations' },
          xaxis: { title: { text: 'Location' }, tickangle: 45 },
          yaxis: { title: { text: 'Crime Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'location_description',
        y_col: 'crime_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.location_description),
          y: data.map((row) => row.crime_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    suspect_joins: [
      {
        query: `SELECT c.primary_type, COUNT(s.suspect_id) as suspect_count FROM crime_chicago c JOIN suspects s ON c.id = s.crime_id GROUP BY c.primary_type ORDER BY suspect_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Crimes with Suspects by Type' },
          xaxis: { title: { text: 'Crime Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Suspect Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'primary_type',
        y_col: 'suspect_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.primary_type),
          y: data.map((row) => row.suspect_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    crime_trend: [
      {
        query: `SELECT strftime('%Y-%m', date) as month, COUNT(*) as crime_count FROM crime_chicago GROUP BY strftime('%Y-%m', date) ORDER BY month;`,
        type: 'line',
        layout: {
          title: { text: 'Crime Trends Over Time' },
          xaxis: { title: { text: 'Month' }, tickangle: 45 },
          yaxis: { title: { text: 'Crime Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'month',
        y_col: 'crime_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.month),
          y: data.map((row) => row.crime_count),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_crime: [
      {
        query: `WITH CrimeCounts AS ( SELECT location_description, COUNT(*) as crime_count FROM crime_chicago GROUP BY location_description ) SELECT location_description, crime_count FROM CrimeCounts WHERE crime_count > 100 ORDER BY crime_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'High-Risk Areas (Crimes > 100)' },
          xaxis: { title: { text: 'Location' }, tickangle: 45 },
          yaxis: { title: { text: 'Crime Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'location_description',
        y_col: 'crime_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.location_description),
          y: data.map((row) => row.crime_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_crime: [
      {
        query: `SELECT primary_type, location_description, COUNT(*) as crime_count FROM crime_chicago GROUP BY primary_type, location_description ORDER BY crime_count DESC LIMIT 10;`,
        type: 'bar',
        layout: {
          title: { text: 'Top 10 Crime Type & Location Combinations' },
          xaxis: { title: { text: 'Crime Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Crime Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'primary_type',
        y_col: 'crime_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.primary_type),
          y: data.map((row) => row.crime_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
  },
  farming: {
    ndvi_overview: [
      {
        query: `SELECT soil_type, AVG(yield) as avg_yield FROM farming_yield GROUP BY soil_type ORDER BY avg_yield DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Yield by Soil Type' },
          xaxis: { title: { text: 'Soil Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Yield' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'soil_type',
        y_col: 'avg_yield',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.soil_type),
          y: data.map((row) => row.avg_yield),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    yield_by_crop: [
      {
        query: `SELECT soil_type, yield FROM farming_yield ORDER BY soil_type;`,
        type: 'histogram',
        layout: {
          title: { text: 'Yield Distribution by Soil Type' },
          xaxis: { title: { text: 'Yield' } },
          yaxis: { title: { text: 'Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'yield',
        y_col: null,
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.yield),
          type: 'histogram',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    soil_joins: [
      {
        query: `SELECT s.soil_type, AVG(f.yield) as avg_yield FROM farming_yield f JOIN soil_data s ON f.id = s.id GROUP BY s.soil_type ORDER BY avg_yield DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Yield by Soil Type' },
          xaxis: { title: { text: 'Soil Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Yield' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'soil_type',
        y_col: 'avg_yield',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.soil_type),
          y: data.map((row) => row.avg_yield),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    yield_trend: [
      {
        query: `SELECT strftime('%Y', year) as year, AVG(yield) as avg_yield FROM farming_yield GROUP BY strftime('%Y', year) ORDER BY year;`,
        type: 'line',
        layout: {
          title: { text: 'Yield Trends Over Time' },
          xaxis: { title: { text: 'Year' } },
          yaxis: { title: { text: 'Average Yield' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'year',
        y_col: 'avg_yield',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.year),
          y: data.map((row) => row.avg_yield),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_soil: [
      {
        query: `WITH YieldBySoil AS ( SELECT s.soil_type, AVG(f.yield) as avg_yield FROM farming_yield f JOIN soil_data s ON f.id = s.id GROUP BY s.soil_type ) SELECT soil_type, avg_yield FROM YieldBySoil WHERE avg_yield > (SELECT AVG(yield) FROM farming_yield) ORDER BY avg_yield DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'High-Yield Soil Types' },
          xaxis: { title: { text: 'Soil Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Yield' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'soil_type',
        y_col: 'avg_yield',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.soil_type),
          y: data.map((row) => row.avg_yield),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_farm: [
      {
        query: `SELECT f.soil_type, s.soil_type as soil_type_data, AVG(f.yield) as avg_yield FROM farming_yield f JOIN soil_data s ON f.id = s.id GROUP BY f.soil_type, s.soil_type ORDER BY avg_yield DESC LIMIT 10;`,
        type: 'bar',
        layout: {
          title: { text: 'Top 10 Soil Type Combinations by Yield' },
          xaxis: { title: { text: 'Soil Type' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Yield' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'soil_type',
        y_col: 'avg_yield',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.soil_type),
          y: data.map((row) => row.avg_yield),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
  },
  finance: {
    transaction_select: [
      {
        query: `SELECT ticker, COUNT(*) as transaction_count FROM finance_stocks GROUP BY ticker ORDER BY transaction_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Transactions by Ticker' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'ticker',
        y_col: 'transaction_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.ticker),
          values: data.map((row) => row.transaction_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
    balance_by_account: [
      {
        query: `SELECT ticker, SUM(close) as total_balance FROM finance_stocks GROUP BY ticker ORDER BY total_balance DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Balance by Ticker' },
          xaxis: { title: { text: 'Ticker' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Balance' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'ticker',
        y_col: 'total_balance',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.ticker),
          y: data.map((row) => row.total_balance),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    fraud_joins: [
      {
        query: `SELECT ticker, COUNT(*) as transaction_count FROM finance_stocks GROUP BY ticker ORDER BY transaction_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Transactions by Ticker' },
          xaxis: { title: { text: 'Ticker' }, tickangle: 45 },
          yaxis: { title: { text: 'Transaction Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'ticker',
        y_col: 'transaction_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.ticker),
          y: data.map((row) => row.transaction_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    balance_trend: [
      {
        query: `SELECT strftime('%Y-%m', date) as month, SUM(close) as total_balance FROM finance_stocks GROUP BY strftime('%Y-%m', date) ORDER BY month;`,
        type: 'line',
        layout: {
          title: { text: 'Balance Trends Over Time' },
          xaxis: { title: { text: 'Month' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Balance' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'month',
        y_col: 'total_balance',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.month),
          y: data.map((row) => row.total_balance),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_fraud: [
      {
        query: `SELECT ticker, SUM(close) as total_amount FROM finance_stocks GROUP BY ticker ORDER BY total_amount DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'High-Value Transactions by Ticker' },
          xaxis: { title: { text: 'Ticker' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Amount' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'ticker',
        y_col: 'total_amount',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.ticker),
          y: data.map((row) => row.total_amount),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_finance: [
      {
        query: `SELECT ticker, COUNT(*) as transaction_count FROM finance_stocks GROUP BY ticker ORDER BY transaction_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Transaction Volume by Ticker' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'ticker',
        y_col: 'transaction_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.ticker),
          values: data.map((row) => row.transaction_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
  },
  sports: {
    match_select: [
      {
        query: `SELECT player_id, COUNT(*) as game_count FROM nba_games GROUP BY player_id ORDER BY game_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Games by Player' },
          xaxis: { title: { text: 'Player ID' }, tickangle: 45 },
          yaxis: { title: { text: 'Game Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'player_id',
        y_col: 'game_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.player_id),
          y: data.map((row) => row.game_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    score_by_team: [
      {
        query: `SELECT player_id, AVG(points) as avg_score FROM nba_games GROUP BY player_id ORDER BY avg_score DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Average Score by Player' },
          xaxis: { title: { text: 'Player ID' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Score' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'player_id',
        y_col: 'avg_score',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.player_id),
          y: data.map((row) => row.avg_score),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    player_joins: [
      {
        query: `SELECT s.player_id, COUNT(*) as shot_count FROM nba_games g JOIN shot_zones s ON g.player_id = s.player_id GROUP BY s.player_id ORDER BY shot_count DESC LIMIT 10;`,
        type: 'bar',
        layout: {
          title: { text: 'Top 10 Players by Shot Count' },
          xaxis: { title: { text: 'Player ID' }, tickangle: 45 },
          yaxis: { title: { text: 'Shot Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'player_id',
        y_col: 'shot_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.player_id),
          y: data.map((row) => row.shot_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    score_trend: [
      {
        query: `SELECT strftime('%Y-%m', game_date) as month, AVG(points) as avg_score FROM nba_games GROUP BY strftime('%Y-%m', game_date) ORDER BY month;`,
        type: 'line',
        layout: {
          title: { text: 'Scoring Trends Over Time' },
          xaxis: { title: { text: 'Month' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Score' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'month',
        y_col: 'avg_score',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.month),
          y: data.map((row) => row.avg_score),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_player: [
      {
        query: `WITH PlayerScores AS ( SELECT s.player_id, SUM(s.made) as total_score FROM shot_zones s GROUP BY s.player_id ) SELECT player_id, total_score FROM PlayerScores ORDER BY total_score DESC LIMIT 10;`,
        type: 'bar',
        layout: {
          title: { text: 'Top 10 Scoring Players' },
          xaxis: { title: { text: 'Player ID' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Score' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'player_id',
        y_col: 'total_score',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.player_id),
          y: data.map((row) => row.total_score),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_sports: [
      {
        query: `SELECT s.shot_zone, COUNT(*) as shot_count FROM nba_games g JOIN shot_zones s ON g.player_id = s.player_id GROUP BY s.shot_zone ORDER BY shot_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Shot Distribution by Zone' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'shot_zone',
        y_col: 'shot_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.shot_zone),
          values: data.map((row) => row.shot_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
  },
  social: {
    post_select: [
      {
        query: `SELECT created_at, COUNT(*) as post_count FROM tweets GROUP BY created_at ORDER BY post_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Posts by Date' },
          xaxis: { title: { text: 'Date' }, tickangle: 45 },
          yaxis: { title: { text: 'Post Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'created_at',
        y_col: 'post_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.created_at),
          y: data.map((row) => row.post_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    engagement_by_type: [
      {
        query: `SELECT text, COUNT(*) as total_posts FROM tweets GROUP BY text ORDER BY total_posts DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Posts by Content' },
          xaxis: { title: { text: 'Content' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Posts' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'text',
        y_col: 'total_posts',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.text),
          y: data.map((row) => row.total_posts),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    user_joins: [
      {
        query: `SELECT u.user_name, COUNT(t.tweet_id) as post_count FROM tweets t JOIN users u ON t.user_id = u.user_id GROUP BY u.user_name ORDER BY post_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Posts by User' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'user_name',
        y_col: 'post_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.user_name),
          values: data.map((row) => row.post_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
    likes_trend: [
      {
        query: `SELECT strftime('%Y-%m', created_at) as month, COUNT(*) as total_posts FROM tweets GROUP BY strftime('%Y-%m', created_at) ORDER BY month;`,
        type: 'line',
        layout: {
          title: { text: 'Posts Over Time' },
          xaxis: { title: { text: 'Month' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Posts' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'month',
        y_col: 'total_posts',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.month),
          y: data.map((row) => row.total_posts),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_engagement: [
      {
        query: `WITH UserEngagement AS ( SELECT u.user_name, COUNT(t.tweet_id) as total_posts FROM tweets t JOIN users u ON t.user_id = u.user_id GROUP BY u.user_name ) SELECT user_name, total_posts FROM UserEngagement WHERE total_posts > 100 ORDER BY total_posts DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'High-Engagement Users (Posts > 100)' },
          xaxis: { title: { text: 'User Name' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Posts' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'user_name',
        y_col: 'total_posts',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.user_name),
          y: data.map((row) => row.total_posts),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_social: [
      {
        query: `SELECT t.created_at, COUNT(*) as total_posts FROM tweets t JOIN users u ON t.user_id = u.user_id GROUP BY t.created_at ORDER BY total_posts DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Engagement by Date' },
          xaxis: { title: { text: 'Date' }, tickangle: 45 },
          yaxis: { title: { text: 'Total Posts' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'created_at',
        y_col: 'total_posts',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.created_at),
          y: data.map((row) => row.total_posts),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
  },
  space: {
    orbit_select: [
      {
        query: `SELECT des, COUNT(*) as object_count FROM space_neo GROUP BY des ORDER BY object_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Objects by Designation' },
          xaxis: { title: { text: 'Designation' }, tickangle: 45 },
          yaxis: { title: { text: 'Object Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'des',
        y_col: 'object_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.des),
          y: data.map((row) => row.object_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    velocity_by_type: [
      {
        query: `SELECT des, AVG(relative_velocity_km_s) as avg_velocity FROM space_neo GROUP BY des ORDER BY avg_velocity DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Average Velocity by Designation' },
          xaxis: { title: { text: 'Designation' }, tickangle: 45 },
          yaxis: { title: { text: 'Average Velocity (km/s)' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'des',
        y_col: 'avg_velocity',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.des),
          y: data.map((row) => row.avg_velocity),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    mission_joins: [
      {
        query: `SELECT is_potentially_hazardous, COUNT(*) as object_count FROM space_neo GROUP BY is_potentially_hazardous ORDER BY object_count DESC;`,
        type: 'pie',
        layout: {
          title: { text: 'Objects by Hazard Status' },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'is_potentially_hazardous',
        y_col: 'object_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          labels: data.map((row) => row.is_potentially_hazardous),
          values: data.map((row) => row.object_count),
          type: 'pie',
          marker: { colors: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444'] },
        }),
      },
    ],
    orbit_trend: [
      {
        query: `SELECT strftime('%Y', close_approach_date) as year, COUNT(*) as object_count FROM space_neo GROUP BY strftime('%Y', close_approach_date) ORDER BY year;`,
        type: 'line',
        layout: {
          title: { text: 'Objects Over Time' },
          xaxis: { title: { text: 'Year' } },
          yaxis: { title: { text: 'Object Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'year',
        y_col: 'object_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.year),
          y: data.map((row) => row.object_count),
          type: 'scatter',
          mode: 'lines+markers',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    cte_payload: [
      {
        query: `WITH HighVelocity AS ( SELECT des, relative_velocity_km_s FROM space_neo WHERE relative_velocity_km_s > 10 ) SELECT des, COUNT(*) as object_count FROM HighVelocity GROUP BY des ORDER BY object_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'High-Velocity Objects (>10 km/s)' },
          xaxis: { title: { text: 'Designation' }, tickangle: 45 },
          yaxis: { title: { text: 'Object Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'des',
        y_col: 'object_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.des),
          y: data.map((row) => row.object_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
    capstone_space: [
      {
        query: `SELECT des, is_potentially_hazardous, COUNT(*) as object_count FROM space_neo GROUP BY des, is_potentially_hazardous ORDER BY object_count DESC;`,
        type: 'bar',
        layout: {
          title: { text: 'Objects by Designation and Hazard Status' },
          xaxis: { title: { text: 'Designation' }, tickangle: 45 },
          yaxis: { title: { text: 'Object Count' } },
          font: { family: 'Inter, sans-serif', color: '#1F2937' },
          margin: { t: 50, b: 100, l: 80, r: 50 },
        },
        x_col: 'des',
        y_col: 'object_count',
        z_col: null,
        group_col: null,
        dataMapper: (data) => ({
          x: data.map((row) => row.des),
          y: data.map((row) => row.object_count),
          type: 'bar',
          marker: { color: '#3B82F6' },
        }),
      },
    ],
  },
};